# Generated by Django 5.0.4 on 2024-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='null', max_length=150)),
                ('data', models.DateField()),
                ('curso', models.CharField(default='null', max_length=150)),
                ('matricula', models.CharField(default='null', max_length=10)),
                ('email', models.EmailField(default='null', max_length=150)),
                ('entrada', models.DateField()),
                ('saida', models.DateField()),
                ('pontos', models.CharField(default='null', max_length=2)),
                ('cargo', models.CharField(default='null', max_length=150)),
                ('info', models.CharField(default='null', max_length=300)),
                ('foto', models.ImageField(default='foto', upload_to='foto')),
            ],
        ),
    ]
