# Generated by Django 5.0.4 on 2024-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='matricula',
            field=models.CharField(default='null', max_length=12),
        ),
    ]
