# Generated by Django 5.0.4 on 2024-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_membro_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='certificado',
            field=models.CharField(default='null', max_length=3, null=True),
        ),
    ]
